
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-deployment
  template:
    metadata:
      labels:
        app: kube-deployment
    spec:
      containers:
      - name: kube-deployment
        image: mohamedessawey/malware-classification:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ports:
        - containerPort: 3000